name: 'Trigger Workflow'
description: 'Trigger another workflow using Octokit'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  owner:
    description: 'Repository owner'
    required: true
  repo:
    description: 'Repository name'
    required: true
  workflow_id:
    description: 'Workflow file name'
    required: true
  ref:
    description: 'Branch reference'
    required: true
runs:
  using: 'node12'
  steps:
    - name: 'Run script'
      run: |
        const { Octokit } = require('@octokit/rest');
        const core = require('@actions/core');
        
        const octokit = new Octokit({ auth: core.getInput('token') });
        
        async function run() {
          try {
            const response = await octokit.rest.actions.createWorkflowDispatch({
              owner: core.getInput('owner'),
              repo: core.getInput('repo'),
              workflow_id: core.getInput('workflow_id'),
              ref: core.getInput('ref'),
            });
            console.log(response);
          } catch (error) {
            console.error(error);
            process.exit(1);
          }
        }
        
        run();
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
