name: Portfolio Deployment

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://akshay-portfoliyo --delete

    - name: Trigger another workflow
      uses: actions/github-script@v6
      with:
        script: |
          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
          const response = await octokit.actions.createWorkflowDispatch({
            owner: 'onlineresultsite',
            repo: 'my-selenium-tests',
            workflow_id: 'main.yml',
            ref: 'main'
          });
          console.log(response);
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
